name: dycodec
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.11.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - alembic==1.17.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.8
      - anyio==4.11.0
      - argbind==0.3.9
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.0.1
      - autopage==0.5.2
      - babel==2.17.0
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - bitarray==3.7.2
      - bleach==6.2.0
      - brotli==1.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cliff==4.11.0
      - cloudpickle==3.1.1
      - cmaes==0.12.0
      - cmd2==2.7.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - comm==0.2.3
      - contourpy==1.3.2
      - cqt-nsgt-pytorch==0.0.10
      - cqt-pytorch==0.0.5
      - cryptography==46.0.2
      - cycler==0.12.1
      - cython==3.1.4
      - data-science-types==0.2.23
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - descript-audio-codec==1.0.0
      - descript-audiotools==0.7.2
      - distance==0.1.3
      - docker-pycreds==0.4.0
      - docstring-parser==0.17.0
      - einops==0.8.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fairseq==0.12.2
      - fastapi==0.119.1
      - fastjsonschema==2.21.2
      - ffmpeg==1.4
      - ffmpy==0.6.3
      - filelock==3.20.0
      - fire==0.7.1
      - flatbuffers==25.9.23
      - flatten-dict==0.4.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - future==1.0.0
      - g2p-en==2.1.0
      - gammatone==1.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==5.49.1
      - gradio-client==1.13.3
      - greenlet==3.2.4
      - groovy==0.1.2
      - grpcio==1.75.1
      - h11==0.16.0
      - h5py==3.11.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - hydra-core==1.0.7
      - idna==3.11
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - iniconfig==2.3.0
      - ipykernel==7.0.1
      - ipympl==0.9.4
      - ipython==8.37.0
      - ipython-genutils==0.2.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==2.4
      - jsonschema==4.22.0
      - jsonschema-specifications==2025.9.1
      - julius==0.2.7
      - jupyter==1.0.0
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kaldiio==2.18.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - lightning==2.3.3
      - lightning-utilities==0.11.2
      - line-profiler==4.1.3
      - llvmlite==0.45.1
      - lxml==6.0.2
      - mako==1.3.10
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - markupsafe==3.0.3
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - mock==5.2.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.1
      - nltk==3.9.2
      - nose==1.3.7
      - notebook==7.2.3
      - notebook-shim==0.2.4
      - npy-append-array==0.9.19
      - numba==0.62.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.0.5
      - onnxruntime-gpu==1.18.0
      - openai-whisper==20250625
      - opt-einsum==3.4.0
      - optuna==2.10.1
      - orjson==3.11.3
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - paramiko==3.4.0
      - parso==0.8.5
      - pastel==0.2.1
      - pesq==0.0.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - pip==24.0
      - pip-chill==1.0.3
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - poethepoet==0.10.0
      - pooch==1.8.2
      - portalocker==3.2.0
      - positional-encodings==6.0.3
      - pot==0.9.6.post1
      - prettytable==3.16.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==3.19.6
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==16.1.0
      - pybind11==3.0.1
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyloudnorm==0.1.1
      - pynacl==1.6.0
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - pyroomacoustics==0.7.4
      - pysepm==0.1
      - pystoi==0.4.1
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyworld==0.3.5
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - randomname==0.2.1
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.2.0
      - rich-argparse==1.7.1
      - rpds-py==0.27.1
      - ruff==0.14.1
      - sacrebleu==2.5.1
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - schedulefree==1.2.7
      - scikit-learn==1.5.0
      - scipy==1.12.0
      - sdeint==0.3.0
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.42.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - sox==1.5.0
      - soxr==1.0.0
      - speechmos==0.0.1.1
      - sqlalchemy==2.0.44
      - srmrpy==1.0
      - stack-data==0.6.3
      - starlette==0.48.0
      - stevedore==5.5.0
      - submitit==1.5.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tinycss2==1.4.0
      - tinydb==4.8.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.3.0
      - torch-complex==0.4.4
      - torch-pesq==0.1.2
      - torch-stoi==0.2.3
      - torchaudio==2.3.0
      - torchcde==0.2.5
      - torchcfm==1.0.7
      - torchdiffeq==0.2.3
      - torchdyn==1.0.6
      - torchinfo==1.8.0
      - torchmetrics==1.4.0.post0
      - torchode==0.2.0
      - torchsde==0.2.6
      - torchtyping==0.1.5
      - torchvision==0.18.0
      - tornado==6.5.2
      - tqdm==4.66.4
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.57.1
      - triton==2.3.0
      - typeguard==4.4.4
      - typer==0.20.0
      - types-python-dateutil==2.9.0.20251008
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wandb==0.17.0
      - wcwidth==0.2.14
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - whisper==1.1.10
      - widgetsnbextension==4.0.14
      - yarl==1.22.0
prefix: /mnt/speech/luyongkang/anaconda3/envs/flowdec
